version: '3.8'

volumes:
  postgres-data:

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Evita que el contenedor se detenga inmediatamente
    command: sleep infinity

    # Usa la misma red que la DB, permitiendo "forwardPorts" en devcontainer.json
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: UTC  # Define la zona horaria explícitamente

    ports:
      - "5423:5432"  # Expose PostgreSQL default port 5432 on 5423

